### ISSUE TITLE
Low in-radio voice volume while whispering

### ISSUE THREAD

**Issue by serraedoardo** [IDI-Systems/acre2#1047]
As of now, regardless of the selected voice volume, the in-radio voice is always heard at the same volume; whilst in reality (I believe) if someone whispers or shouts via radio, his voice is heard quieter or louder by whoever listens.

**Solution I'd like:**
I get the idea of not playing the in-radio voice louder when who is transmitting is shouting, as to deafen the players in seek of immersion is not pleasant. However, the possibility of adding an option to play the in-radio voice quieter while whoever speaks is whispering might be taken into consideration.
In my opinion, such an option would increase the tension in some TvT events by a significant amount, as it forces the players to increase their voice volume to be heard clearly.

**Comment by jonpas** [comment]
There are 2 ways to look at this:

1. Determining volume from microphone input. This has been attempted years ago and due to different configurations, headphones, sound systems and so on, is impossible to do correctly and did not end up as an enjoyable experience. However, I am assuming this issue is not about that.

2. Using the existing volume slider to determine volume of the voice through radio as well. Currently volume slider is only taken into account for direct speech. While this is doable in contrast to 1, I still don't think it's very true to life. You can easily tweak microphone position so you can whisper and will still be heard fairly normally over the radio (more or less just changed pitch, not so much volume), as volume itself is more determined on the radio specs. @IDI-Systems/acre-managers may correct me on this with more experience than I have.
