### ISSUE TITLE
Player after spawned doesn't hear other players

### ISSUE THREAD

**Issue by Deadshot37cz** [IDI-Systems/acre2#1126]
Hi, 

our clan started to encounter a new probably bug, after the player spawned can't hear other people, even if they do.

**Comment by Drofseh** [comment]
Fill out the issue template that you deleted

**Mods (complete and add to the following information):**
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
- **ACRE2:** `2.x.x` [e.g. 2.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!_

**Description:**
A clear and concise description of what the bug is.

**Steps to reproduce:**
- Go to ...
- Click ...
- See ...

**Expected behavior:**
A clear and concise description of what you expected to happen.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the extension log file, which can be found at `<Arma 3 directory>\logs\acre_dll.log`.

**Additional context:**
Add any other context about the problem here.

**Screenshots:**
If applicable, add screenshots to help explain your problem.

**Comment by jonpas** [comment]
No info provided.
