### ISSUE TITLE
Option to mute self

### ISSUE THREAD

**Issue by ghost** [IDI-Systems/acre2#1137]
**Is your feature request related to a problem?**
Currently whenever I try to mute myself, Acre2 unmutes me after a couple seconds. As a pilot that uses a HOTAS, I use voice activity since it's much easier to communicate with my passengers and crew members when flying. I also haven't found a way to bind two different keybinds for PTT.

**Solution you'd like:**
The ability to mute yourself in Teamspeak 3.

**Alternatives you've considered:**
None (Like I said, voice activity is easier as a pilot).

**Additional context:**
No additional context, but I'd like to know why this "feature" was implemented in the first place. There was a issue that said this was by design which baffles me.

**Comment by PabstMirror** [comment]
Are you using the "Start broadcast" ace interaction?
We could probably add a "toggle broadcast" keybind that would mimic that action

**Comment by veteran29** [comment]
You can use "toggle away status" to mute your microphone. ACRE won't touch that.
![image](https://user-images.githubusercontent.com/4293906/134707765-2c2a1077-043a-4b9f-96e2-21533f66de0c.png)

**Comment by jonpas** [comment]
> No additional context, but I'd like to know why this "feature" was implemented in the first place. There was a issue that said this was by design which baffles me.

I believe it was explained in that same issues, but short story, things evolve and were definitely not the same back then. May not be the same today anymore, it was a deeper technical issue.

We are open to changing that, but I don't think anyone from the team will put much time into it. Contributions welcome.

**Comment by MoshPit86** [comment]
I'm having the same situation. I would like to be able to manually mute my mic in TS3 whenever I need to. Since there is this feature called "Unmute Clients", I'm a bit confused because I was expecting this to be the option to toggle "force unmute". It is turned off/not active (aka not checked, see here: https://prnt.sc/1u7xylz) on our server, ACRE2 still keeps unmuting manually muted clients. Is there a way to circumvent this other than the PTT option in TS3?

**Comment by MoshPitCodes** [comment]
I'm having the same situation. I would like to be able to manually mute my mic in TS3 whenever I need to. Since there is this feature called "Unmute Clients", I'm a bit confused because I was expecting this to be the option to toggle "force unmute". It is turned off/not active (aka not checked, see here: https://prnt.sc/1u7yi8p) on our server, ACRE2 still keeps unmuting manually muted clients. 

Is there a way to circumvent this other than the PTT option in TS3? Voice Activation is required in a lot of scenarios to be able to operate effectively. Also, most players already have a plethora of keybinds. This should not be a feature that takes away control from the user. Besides that, I'm really not keen to setup different keybinds for different use cases (e.g. I would use the same button for PTT as the in-game one for radio transmission in Arma, which would require a separate one for talking locally. But those buttons would be matched to something else in other games, which would require me to rebind them in-game or use different ones for PTT. Or I would be required to change between PTT and VA every time in TS3). I really cannot be bothered to do all that, it's just straight up inconvenience. It's something that made me drop ACRE for TFAR a long time ago and I'm really happy to do it again if the ACRE team still won't do anything about it, even though it has been requested multiple times in the past. 

I'm really not intending to sound entitled or like a jerk, but the answer that it's "by design" really doesn't cut it here.

**Comment by veteran29** [comment]
I just mentioned a way to mute yourself 2 comments above... 

You can also bind it to a key:
![image](https://user-images.githubusercontent.com/4293906/135493230-242ba068-4f6f-41d2-961c-96bdae56f055.png)

**Comment by MoshPitCodes** [comment]
@veteran29 Toggling the Away Status in Teamspeak is no option because it not only mutes the client's microphone but also the speakers. There are many situation in which I do want my microphone to be muted but still be able to listen to comms and have Voice Activation enabled when unmuting. So, is there a proper solution to this? meaning: when can we expect to have this feature implemented properly instead of bruteforcing things on the clients that players don't want? I mean, there is literally a CBA setting that is related to this but is just ignored or not working correctly.

**Comment by veteran29** [comment]
Toggling away does not mute speakers for me so it might be how your TS is configured. Also, don't ask me when it will be implemented as I'm not part of the dev team. AFAIK, IDI-Systems has a lot of more important things to work on currently so taking things into your own hands and making a contribution is the best way to get it changed.

**Comment by ChaosRifle** [comment]
insane this is still an issue and not planned. literally can dox you, this is a huge problem.
