### ISSUE TITLE
Muffle or disable ability to talk under water

### ISSUE THREAD

**Issue by edelle** [IDI-Systems/acre2#125]

**Comment by Sniperhid** [comment]
In the changelog of 2.3.0 - 
`[New] Talking underwater is now disabled. SDV now has intercom. Broadcasting on radio underwater should also work.`

In essence this is already the case except that you can still transmit/recieve on a radio - This is a compromise for now due to the fact we have not implemented any underwater radios.

**Comment by edelle** [comment]
sorry about that, shouldn't have suggested that
