### ISSUE TITLE
Constant TeamSpeak Freezes with TeamSpeak v3.6.0

### ISSUE THREAD

**Issue by NHarrison25** [IDI-Systems/acre2#1258]
**Mods:**
- **Arma 3:** 2.12.150301 stable
- **CBA:** 3.15.8 stable
- **ACRE2:** 2.11.0.1054 stable
- **ACE:** 3.15.2 stable
- Please see the RPT files for the rest. None of them actually modify or have previously conflicted with ACRE, to my knowledge.

**Description:**
When on a server with a sizeable number of players (~55+, only fighting against AI enemies), players on TeamSpeak v3.6.0 will be in a constant cycle of playing for a little while (30 min - 1 hour), before having their TeamSpeak stop responding and being kicked off of the server for a generic "Steam Ticket Check" error. Until they manually alt-tab and force close their TeamSpeak client, their entire system is unresponsive and slow. Alt-tabbing before being kicked off of the server, force closing TeamSpeak, and reconnecting to the TeamSpeak server can prevent a disconnection from the game server. Typically, this issue is also accompanied by the last bit of audio they received (either local VOIP or a radio transmission) looping repeatedly until TeamSpeak is closed.

Though I have yet to personally see this reproduced in my unit, I know of other units with the identical issue, with different mods, and I will endeavor to have them add any information they have to this issue.

**Steps to reproduce:**
- Uncertain

**Expected behavior:**
N/A

**Where did the issue occur?**
- Dedicated

**Log Files:**
- [Client RPT (Pre-freeze)](https://gist.github.com/NHarrison25/b199d663ab9fb3cd62cfc05c2c48d373)
- [Client RPT (Post-freeze relaunch)](https://gist.github.com/NHarrison25/9e8bdd7a9ce4539750b5ba204cbb1167)
- [TS3 Client Log for above user](https://gist.github.com/NHarrison25/5c377cbb4e7404e0bf2134dc58246344)
- [TS3 Client Log for different user](https://gist.github.com/NHarrison25/58326654bd820786d7a08bef0afa0d17)
- [Server RPT](https://gist.github.com/NHarrison25/32ccac6af07037976509403549e7c941)

**Additional context:**
- I am unable to provide TS3 or ARMA crash dump files, because neither were generated for any of the dozens of players who froze up throughout the night (thus it is technically not a crash).
- This is confirmed as not occurring for players on TeamSpeak v3.5.6, who also have the newest ACRE plugin version.

**Screenshots:**
- [Discord Chat Log 1](https://i.imgur.com/99s1TEE.png)
- [Discord Chat Log 2](https://i.imgur.com/q9eOAf6.png)

**Comment by MildlyInterested** [comment]
My unit has been experiencing the same issue, ~60 player OPS only fighting against AI, TS freezing causes Arma to freeze, killing TS will unfreeze Arma. 
Downgrading players to Teamspeak version 3.5.6. has completely resolved the issue so it must with something introduced with Teamspeak 3.6.0.

**Comment by dedmen** [comment]
When  TS is frozen, go into task manager. Details panel.
Right click on the teamspeak process and choose "Create Minidump" (I don't know what it exactly says in english, dump, dump memory, something like that)
That will record teamspeaks current state, that can then be opened in a debugger to see where it is frozen, or rather what it was doing while the dump was created

**Comment by PabstMirror** [comment]
I have one dump but getting a 2nd would be a big help to compare with

Looks like it's in a `setMuted` at the same time as a `onEditPlaybackVoice..`
It's also running `ConnectNamedPipe` which I'm worried is related to the locking up of the arma plugin
![Untitled](https://github.com/IDI-Systems/acre2/assets/9376747/5e5802dd-b39b-4b9a-af82-5688723000d1)

the [teamspeak 3.6.0 patch note](https://community.teamspeak.com/t/teamspeak-3-client-3-6-0/41112) are pretty light and don't really mention anything that seems relevant.
There also seem to be many non-acre users having stability problems with it

**Comment by k-e-l-p** [comment]
+1.
My unit has been experiencing consistent crashes for almost everyone involved. I counted 6 crashes for myself last OP. Same nature of crash as the posts above. Same workarounds also work.

Please fix.

**Comment by k-e-l-p** [comment]
I Do have some additional dumps, however, I'm unsure of their validity (i run on linux, may be an entirely different issue), I do know that they were generated in the right timeframe for this issue.

[ts3dump_1688326543208.zip](https://github.com/IDI-Systems/acre2/files/12063027/ts3dump_1688326543208.zip)
[ts3dump_1687639372417.zip](https://github.com/IDI-Systems/acre2/files/12063029/ts3dump_1687639372417.zip)

I'll see if anyone else in my unit has any additional dumps to work with.

**Comment by dedmen** [comment]
Amazing, that looks like a Deadlock on Teamspeak's side. Should be able to just send them that and have them fix it.
I can look closer but I'll also need the specific teamspeak .exe file used for the dump.

A workarond for ACRE could be, to put a mutex around TS3Client API.
Eg don't call setClientMetadata and setMuted at the same time. That way you have the freeze inside your code, instead of deadlocking inside Teamspeak's code.

Teamspeak warned me years ago that you shouldn't call Teamspeak API functions (like muting clients) from inside audio callbacks (like onEditPlaybackVoiceDataEvent shown in screenshot) which TFAR is doing.

I assume they have some kind of "plugin interaction" lock. Its locked around the processVoiceData event, so all other threads will be frozen while you're in there. Question then is, what is that lock that ACRE is taking inside processVoiceData?

But you aren't doing that, you are calling it from a different thread. And TFAR is doing that "bad" stuff, but doesn't have freeze issues so far.

> It's also running ConnectNamedPipe which I'm worried is related to the locking up of the arma plugin
But the pipe thread doesn't seem to be doing anything?

It looks like its in here https://github.com/IDI-Systems/acre2/blob/19e6b2f10c9885f7d1d2df30a204f785bd055adb/extensions/src/ACRE2Core/NamedPipeServer.cpp#L148 ? 
But that shouldn't happen? It wouldn't usually get disconnected?

As far as I can see the game side shouldn't freeze as you do everything async. Except maybe the NamedPipe buffer is full, and the Write request is blocking waiting for buffer space to become available?

**Comment by dedmen** [comment]
There is the lock inside the voice event
https://github.com/IDI-Systems/acre2/blob/19e6b2f10c9885f7d1d2df30a204f785bd055adb/extensions/src/ACRE2Core/SoundEngine.cpp#L32

Maybe also this lock on player that's speaking
https://github.com/IDI-Systems/acre2/blob/19e6b2f10c9885f7d1d2df30a204f785bd055adb/extensions/src/ACRE2Core/SoundEngine.cpp#L35

(uff.. use RAII for locks please, its been in the standard since C++11...)

updateSpeakingData also locks the player
https://github.com/IDI-Systems/acre2/blob/19e6b2f10c9885f7d1d2df30a204f785bd055adb/extensions/src/ACRE2Core/updateSpeakingData.h#L35

And calls setMuted
https://github.com/IDI-Systems/acre2/blob/19e6b2f10c9885f7d1d2df30a204f785bd055adb/extensions/src/ACRE2Core/updateSpeakingData.h#L80

I think I got it.

MutexA is teamspeak and most likely a recursive mutex that is around all plugin interactions.
MutexPlayer is yours.


Code flow as follows
// is what would happen next, if we weren't locked up
<--- is pointing at where the code is currently at in your screenshot

Thread1:
Teamspeak locks MutexA
CSoundEngine::onEditPlaybackVoiceDataEvent fires
SoundEngine locks MutexPlayer <--- Stuck, updateSpeakingData is holding lock
// SoundEngine unlocks MutexPlayer
// Teamspeak unlocks MutexA after onEditPlaybackVoiceDataEvent returns

Thread2 (ACRE worker thread):
Received updateSpeakingData request, for the same player who's voice data is currently processed
updateSpeakingData::call locks MutexPlayer
code calls CTS3Client::setMuted
Teamspeak locks MutexA <---Stuck, onEditPlaybackVoiceDataEvent is holding lock
// Teamspeak processes the mute
// Teamspeak unlocks MutexA
// updateSpeakingData unlocks MutexPlayer


A classic deadlock scenario.

Simplest solution, make SpeakingType atomic, so you don't need a lock on it for `onEditPlaybackVoiceDataEvent`
The `player->channels[i]` is anyway protected by the soundMixer lock...

But actually, you are taking the sound mixer lock too high up here:
https://github.com/IDI-Systems/acre2/blob/19e6b2f10c9885f7d1d2df30a204f785bd055adb/extensions/src/ACRE2Core/updateSpeakingData.h#L33

This will just lead to the exact same deadlock again as you are calling Teamspeak API functions, from within sound mixer lock.
Move the mixer lock down to only guard regions that access `speaker->channels` without having TS API calls inbetween.

Now that I see that the sound mixer lock is too high up. The "MutexPlayer" that I listed above, could also be "MutexSoundMixer" leading to same end result.

**Comment by jonpas** [comment]
> (uff.. use RAII for locks please, its been in the standard since C++11...)

ACRE is from way before. :P

Great investigation othwerise! :+1:
