### ISSUE TITLE
Point or Comma in 117

### ISSUE THREAD

**Issue by Frostie2811** [IDI-Systems/acre2#235]
Arma 3 Version: 1.66 (stable)
CBA Version: 3.x.x (stable)
ACRE2 Version: 2.4.0 (stable)

Mods:

- @CBA_A3
- @acre2
- @ACE3 3.8.3

**Description:**
Some People had a . in the frequenzy settings and some others a , so there are problems with setting it right up. Taking up a new radio didnt fixed it. We didnt Try a rejoin

**Steps to reproduce:**
- Just opening up the set up frequenzy on the 117

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- ACRE Modules
- ACE Modules

**Comment by Sniperhid** [comment]
`so there are problems with setting it right up. ` - What problems?

It does seem `CBA_fnc_formatNumber` does localise the decimal separator and it's only a dot in English otherwise it's a comma -> https://github.com/CBATeam/CBA_A3/blob/dda0cf9489e96ed83a9229f04ddc34397d2b9f73/addons/strings/stringtable.xml#L8

**Comment by Frostie2811** [comment]
We have found that the guys with the English installed version can change the frequency behind the point. The guys with the German version which have a comma couldnt when they go to the place and want to change the digit it always change to a 0.

**Comment by PabstMirror** [comment]
String `STR_CBA_FORMAT_NUMBER_DECIMAL_POINT` isn't used in CBA_fnc_formatNumber;
Since CBA 3.2 which came out last night.
As far as I know the game expects dots, so this might be fixed?

This also means non-english will see `1000.5` as `1.000.5` when using the separate thousands option, which isn't ideal, but I don't think that is used in ACRE.

**Comment by Sniperhid** [comment]
Thanks for the heads up @PabstMirror - @Frostie2811 can you get guys to update their CBA and see what happens?

**Comment by Frostie2811** [comment]
i will look it by myself because i have also the german version installed.

**Comment by Frostie2811** [comment]
Just checked it and with the new version of CBA the problem is solved.

**Comment by Sniperhid** [comment]
Awesome thanks!
