### ISSUE TITLE
TS3 crashes while clicking on a user in TS who has TFAR 1.0 enabled

### ISSUE THREAD

**Issue by jakdax99rb** [IDI-Systems/acre2#419]
**Arma 3 Version:** `1.76` (stable)
**CBA Version:** `3.4.1` (stable)
**ACRE2 Version:** `2.5.0` (stable)

**Mods:**
---
Not encountered in game so no mods other than the ACRE plugin and Beta TFAR 1.0 plugin
---

**Description:**
- TS3.1 crashes when clicking on someone who has the TFAR 1.0 plugin enabled while either ACRE 2.5.0 or 2.4.2 plugins are enabled on the client. You do not have to be in game for this to occur. 
 
**Steps to reproduce:**
- Get 2 people
- Person A loads the TFAR 1.0 plugin
- Person B loads the ACRE plugin
- Person B clicks on person A's name in TS
- Person B crashes

**Where did the issue occur?**
- Out of game on TS3.1

If you guys dont have access to the TFAR 1.0 let me know and I can get the plugin over to you guys for testing.

**Comment by TheMagnetar** [comment]
I am unsure if this is totally within our scope to fix since this may be totally dependant on another mod or even TS itself.
Having said that: does this happen as well with the stable TFAR release? Also, make sure to open the same issue on the TFAR side.

**Comment by jakdax99rb** [comment]
TS3 does not crash when ACRE2 plugin is enabled and the person you are clicking on has TFAR 0.9.12 plugin enabled.

**Comment by dedmen** [comment]
@TheMagnetar Open the same issue on TFAR side because ACRE's meta info parsing is crashing TS? No..
I already got the report a year ago and redirected the reporter to tell the ACRE team. Seems like he never did.

Any other plugin can put ANYTHING inside the clients metainfo. And if ACRE can't handle something of that anything then it's not the plugins fault that put the data in there.

**Comment by jonpas** [comment]
Would be nice if you'd just tell us what you discovered a year ago when you added those 4 lines of data to metainfo, instead of blaming some random guy who didn't report. :D

TS' metainfo was not designed for that much metainfo it seems, their examples use 128 bytes as well, I guess no one thought someone would write that much to it.

**Comment by dedmen** [comment]
I didn't discover anything. But It is not a Teamspeak issue. Otherwise other TFAR users would also crash.

**Comment by jonpas** [comment]
Not saying it's a TeamSpeak issue, just that they seem to never thought about a lot of text in there.
