### ISSUE TITLE
Publish TS Addon on myTeamspeak

### ISSUE THREAD

**Issue by Bluscream** [IDI-Systems/acre2#424]
To auto push updates you could submit your plugin archive to https://www.myteamspeak.com/userarea/addons/create

**Comment by Soldia1138** [comment]
How do we ensure that the correct version of the plugin is loaded? 
Can we tell TS to download a specific version of the plugin (automatically, depending on the current mod version loaded)?

**Comment by Bluscream** [comment]
You can read the mod version with the plugin and use version dependent functions with if's etc.

**Comment by jonpas** [comment]
We have no need for that, our plugin automatically updates as the mod updates. I see no reason to complicate this.

**Comment by Bluscream** [comment]
The plugin most likely needs more updates than the mod because of the API version changes.

**Comment by Soldia1138** [comment]
Actually no. Every build is a new version/build number. And every new build comes with a new version for the plugin which is, as jonpas stated, automatically copied to the TS Plugins Directory at gamestart.

**Comment by Bluscream** [comment]
Yeah but what if the mod itself doesn't need an update but Teamspeaks plugin API changes? You would need to recompile and push everything.

**Comment by Soldia1138** [comment]
If a new TS API is rolled out, this is generally known to us due to beta versions. We test and if there's an incompatibility, we'll fix it on our side.
Our process is completely CI/CD-driven and we literally just need a few clicks for it. Plus we are heading for build number 1000 and the TS API changed vom v20 to v21 during that 1000 builds.
I see more problems than solutions if we'd push it to myTeamspeak (and nobody needs the plugin, without the mod)

**Comment by Bluscream** [comment]
Well, then.

Another aspect is advertising tho.
