### ISSUE TITLE
972/973 build breaks vanilla lasers/flashlights

### ISSUE THREAD

**Issue by Max255PL** [IDI-Systems/acre2#450]
**Arma 3 Version:** `1.76` (stable)
**CBA Version:** `3.4.1` (stable)
**ACRE2 Version:** `2.5.1` (dev build 972 / RC build 973)

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
- Vanilla lasers/flashlights won't stay turned on with newest ACRE loaded (both 972 and 973), pressing the key makes them flash quickly and then turn off.

**Steps to reproduce:**
- Needs a simple mission: night time, NATO Recon Team Leader.
- In game when in NVGs, try to turn the laser on, watch it instantly turn off.

**Where did the issue occur?**
- Editor (Singleplayer).

**Placed Modules:**
- None.

**RPT log file:**
- https://pastebin.com/jTGn5fYj

**Comment by PabstMirror** [comment]
Manually setting `acre_sys_core_arsenalOpen = true` fixes the issue, so probably related to that recent change

**Comment by jonpas** [comment]
Fixed by #452. Related to optimizing with lower-casing, it was continuously running this line https://github.com/IDI-Systems/acre2/blob/218a364ebe0d6ef3aea136ccfdf87cfe3650e23b/addons/sys_radio/fnc_monitorRadios.sqf#L31 because `ItemRadioAcreFlagged` was never considered to already be added. For some reason `linkItem` causes accessory reset like that.
