### ISSUE TITLE
Acre2 failed to install, TS in non default location.

### ISSUE THREAD

**Issue by Jason-Terry** [IDI-Systems/acre2#817]
**Is your feature request related to a problem?**
When installing acre2, and TS is in a location other than the C drive. Acre2 fails to install.

**Solution you'd like:**
Better support for manual installation.

**Alternatives you've considered:**
Unknown

**Additional context:**
Unknown

**Comment by Drofseh** [comment]
I've pretty much always had TS installed on my D drive and it's always worked fine for me.

Where is your TS plugins folder?
It should be in `C:\Users\Your_Username\AppData\Roaming\TS3Client\plugins`

**Comment by TheMagnetar** [comment]
I also have my users folder installed in D and I experience no issues.

**Comment by Kanthier** [comment]
I have had some issues with acre2 install before (mostly because of TS's end) but it's fairly easy to copy the plugins from the @acre2/plugins folder and paste them into the TS3 AppData and program files plugins folders.
My TS was weird because it seemed to pull plugins from the program files folder unlike everyone else's (also it didn't properly run the plugin installer, but I think that was a registry issue with TS)

The other possibility I can think of is when you launch Arma with acre2 either you have TS open (can cause issues) or maybe it has to be launched as admin and isn't?

**Comment by TheMagnetar** [comment]
Also, can you clarify what do you mean with "better manual support?". As mentioned above, you just need to copy the plugins into the TS folder.

**Comment by TheMagnetar** [comment]
Status update?
