### ISSUE TITLE
Wrong names (Propagation Model) + minor things

### ISSUE THREAD

**Issue by dasP123** [IDI-Systems/acre2#818]
Today we tested ACRE2 settings on our server with:

ACRE2 Vers.: 2.7.1.1016.
Radios: AN/PRC-343, AN/PRC-152 & AN/PRC-117F

ARMA 3 Vers.: 1.94.145977
ACE Vers.: 3.12.6
CBA Vers: 3.12.1.190812

- It happens to be the case, that LOS Multipath and LOS Simple got their names mixed up.
  LOS Simple caused terrain and distance related signal quality decrease, while LOS Multipath 
  didn't.

- Also the effect of the current default terrain coeff. (1.00) seems to have too much of an impact 
   on the  signal strength. We are now using a value of 0.12.

- In addition to that, the new Ground Spike Antenna did not seem to make any difference. 
  However, interaction was possible.

- When using the Micro DAGRE (ACE) there might occure overlay issues with the ACRE HUD 
  while transmitting/selecting radios. The HUD pops up behind the Micro DAGRE. This is 
  occurring since the last patch, but is not constistent.

**Comment by jonpas** [comment]
> When using the Micro DAGRE (ACE) there might occure overlay issues with the ACRE HUD while transmitting/selecting radios. The HUD pops up behind the Micro DAGRE. This is occurring since the last patch, but is not constistent.

This is just the way Arma works, they will get layered on top of each other by the order they were first opened. No solution at this time.

**Comment by TheMagnetar** [comment]
Thank you for the time you put into writing this. Here is the explanation of the "issues" you encountered:

1) LOS Single and LOS Multipath may give different results and it may well be, that the LOS Single Path decreases signal quality. A straight line can be obstructed while a signal that bounces may have a clearer path. 
2) A terrain coefficient of 0.12 for sure gives the radios a wrong range. For a 343 the range is around 700 m in flat terrain but it may well be 20m if then antennas cannot "see themselves".
3) The ground spike only boosts signal power for 152 or 148 (from 5W to 20W). With a terrain coefficient of 0.12, the main advantage of the GSA (height) is lost since terrain already has a low influence on the link budget. GSA are normally used to get an unobstructed link between two antennas by increasing height (mast) or providing clearance and a straight antenna when the RTO is staying behind cover or laying prone for example.
