### ISSUE TITLE
TeamSpeak crashes with multiple servers

### ISSUE THREAD

**Issue by BrettMayson** [IDI-Systems/acre2#855]
**Description:**
TeamSpeak 3 will crash when attempting to connect to multiple servers with the ACRE plugin enabled.

**Steps to reproduce:**
- Enable ACRE
- Join a server
- Join a second server
- CTD

**Expected behavior:**
It doesn't crash

**Comment by jonpas** [comment]
I have done that in the past and it worked fine. Is this from some recent update?

**Comment by BrettMayson** [comment]
I had this today, disabled ACRE and it was fine. No logs or anything with TeamSpeak though so I'm not sure how to debug further

**Comment by nomisum** [comment]
can confirm issue

**Comment by jonpas** [comment]
I can't reproduce this. Does it happen only when ACRE is connected to the game, or also without Arma at all?

**Comment by DeliciousJaffa** [comment]
I can confirm this, happens with no arma open at all, ACRE appears to initialise multiple times, I've seen ACRE loaded twice in the same server tab.
I believe it may just be blindly grabbing data for the current server tab which changes underneath it when you connect to a different server (in a new tab). I've also seen the error `insufficient client permissions (failed on i_channel_permission_modify_power)` in teamspeak when it does this.
I can reliably reproduce this by simply connecting to 3-4 teamspeak servers at startup (Set to auto-connect in the bookmarks), just two servers appears to be fine although I do get crashes trying to connect to further additional servers.

Teamspeak version: 3.3.2 on Windows
ACRE2 plugin: 2.7.2.1022

Edit: My logs look the same as the comment below

**Comment by Freddo3000** [comment]
On 3.5.0 it crashes if you have two or more servers set to connect on startup. If you disable ACRE during startup and then enable it after it doesn't crash.

Edit:  
Here are the logs
[ts3client_2020-03-21__07_42_23.939727.log](https://github.com/IDI-Systems/acre2/files/4362532/ts3client_2020-03-21__07_42_23.939727.log)
[ts3dump_1584772938232.zip](https://github.com/IDI-Systems/acre2/files/4362533/ts3dump_1584772938232.zip)

**Comment by ThymoNL** [comment]
No longer reproducible for me. Most likely fixed by TS themselves. Suggest closing this?

**Comment by jonpas** [comment]
@synixebrett @nomisum @DeliciousJaffa @Freddo3000 can any of you confirm TS 3.5.3 fixes this?

**Comment by Freddo3000** [comment]
I cannot confirm it yet, as it was fairly inconsistent to begin with. Sometimes it would crash, sometimes it wouldn't. When it did crash it would usually crash upon reopening when trying to connect to multiple servers.

Though I haven't experienced it in the last few days.

**Comment by DeliciousJaffa** [comment]
I still get the crash on startup when connecting to 3 servers automatically, not fixed.
![image](https://user-images.githubusercontent.com/2257490/82154200-28fc5b00-9864-11ea-9cb1-502d78ae84ab.png)
![image](https://user-images.githubusercontent.com/2257490/82154204-2c8fe200-9864-11ea-9d9d-eaa45a43fcb3.png)

**Comment by DeliciousJaffa** [comment]
As mentioned earlier, I believe it has something to do with the current tab being changed while the plugin is executing a function. I haven't tested this, but it's probably worth looking into.

My suspicions are with all the `getCurrentServerConnectionHandlerID()`, often within the same functions that could end up executing commands on different connect tabs than intended.
https://github.com/IDI-Systems/acre2/blob/master/extensions/src/ACRE2TS/TS3Client.cpp#L29

i.e. For connecting, a connectStatusChange event occurs which grabs the ID multiple times
https://github.com/IDI-Systems/acre2/blob/master/extensions/src/ACRE2TS/TSCallbacks_init.cpp#L101
This is despite teamspeak giving the ID as part of the call
https://github.com/TeamSpeak-Systems/ts3client-pluginsdk/blob/master/src/plugin.c#L643

Edit: The example may well be the crash (or one of them?), the plugin uses the status teamspeak provides, but gets the id of the current tab instead of the one the event provides, meaning that the plugin would be attempting to execute `getClientID` on a tab which has not yet connected to a server if it's passed `STATUS_CONNECTION_ESTABLISHED` for a different tab than a currently selected yet-to-connect one.

**Comment by Freddo3000** [comment]
Encountered it again
[CrashDumps.zip](https://github.com/IDI-Systems/acre2/files/4655087/CrashDumps.zip)

Was trying to connect to another Teamspeak server, client freshly launched.

**Comment by ThymoNL** [comment]
[ts3dump_1589963426891.zip](https://github.com/IDI-Systems/acre2/files/4655584/ts3dump_1589963426891.zip)

Crashdump with test fix from #956 . Crashed on startup. When loading ACRE after connecting to multiple servers it keeps working.

It crashes on an access violation. I'm not sure if it's caused by the plugin or TS itself.

**Comment by zalexki** [comment]
can confirm it coming from ACRE2 plugin and not ts alone, can provide some crashdumps too

**Comment by Freddo3000** [comment]
So recently something I've noticed is that if I play a mission with ACRE connected, disconnect and disable acre plugin in teamspeak, the next time I start my computer teamspeak will crash as soon as it connects to a second teamspeak server. 

If I close the second connection before it finishes, it will not crash. However if I try to connect later it will crash unless I disable ACRE, which brings me onto a second set of strange behaviour. 

As mentioned first, I disable ACRE before closing teamspeak in order to avoid it crashing when I next start it, however ACRE appears to reenable itself the next time I start it, and promptly crash. Disabling it again allows me to join additional servers, and reenabling ACRE having connected to servers doesn't cause teamspeak to crash.

**Comment by DeliciousJaffa** [comment]
> So recently something I've noticed is that if I play a mission with ACRE connected, disconnect and disable acre plugin in teamspeak, the next time I start my computer teamspeak will crash as soon as it connects to a second teamspeak server.

How are you closing teamspeak? If you let windows close it on shutdown, it tends to not save any changes to which extensions are loaded. You normally have to use the quit option inside Teamspeak in my experiences.

**Comment by Freddo3000** [comment]
@DeliciousJaffa That would be it.

**Comment by hotsumak4** [comment]
I have the problem that I can not transmit on the radio, but I repeat everything they talk ... I have already reinstalled both the mod and the TS3 and it continues as it can be? I report this happens when I am in the game alone I cannot transmit but I restore everything

**Comment by Drofseh** [comment]
@hotsumak4 this issue is about connecting to multiple servers.
Please do not spam multiple unrelated issues, such as this one and #986 , with your problems.

**Comment by Freddo3000** [comment]
Issue seems to persist, however I've noticed a few things.

* It appears to crash when the P-drive finishes mounting (I have it set to mount on start), haven't tried disabling it though.
* If I repeatedly click on the first server that loaded when starting Teamspeak, it does not crash
* Sometimes before it crashes it briefly stutters and connects multiple times to a teamspeak server, up to three times. Rejoining the server shows the duplicate clients, that a few seconds later time out.
* Disabling the plugin while in Arma but not in mission causes Teamspeak to freeze until the game is completely closed
* Disabling and then re-enabling the plugin stops crashes until the next time you launch arma, after which the next time you start Teamspeak it will crash, regardless of whether you disabled the plugin or not. The plugin will have reenabled itself.

**Comment by jonpas** [comment]
I tried this like 2 weeks ago, and being connected to 2 TS servers (2 tabs) did not cause a crash. ACRE2 did always use just one of them (rather inconsistently), but no crash. :thinking:

**Comment by Freddo3000** [comment]
> 
> 
> I tried this like 2 weeks ago, and being connected to 2 TS servers (2 tabs) did not cause a crash. ACRE2 did always use just one of them (rather inconsistently), but no crash. 🤔

For me the issue occurs when you connect to ACRE on a teamspeak server, then restart teamspeak. If you have it set to connect to multiple servers on startup it crashes. If you spam press the first server tab to connect, it will not crash, however if you launch Arma later ACRE will fail to connect.

I could probably screen share the problem on discord or something.

**Comment by jonpas** [comment]
Yeah I understand @Freddo3000, however those are all different than the original issue above. I am fine with tracking it under the same one, because it is clearly connected, but I don't know if the fix would be even in the same ballpark.

**Comment by Alablm** [comment]
> On 3.5.0 it crashes if you have two or more servers set to connect on startup. If you disable ACRE during startup and then enable it after it doesn't crash.
> 
> Edit:
> Here are the logs
> [ts3client_2020-03-21__07_42_23.939727.log](https://github.com/IDI-Systems/acre2/files/4362532/ts3client_2020-03-21__07_42_23.939727.log)
> [ts3dump_1584772938232.zip](https://github.com/IDI-Systems/acre2/files/4362533/ts3dump_1584772938232.zip)

This issue persists in TS 3.5.6 ACRE 2.8.0.1037

[ts3client_2020-11-28__19_40_55.502731.log](https://github.com/IDI-Systems/acre2/files/6050056/ts3client_2020-11-28__19_40_55.502731.log)
[acre2.log](https://github.com/IDI-Systems/acre2/files/6050060/acre2.log)
[ts3dump_1614347856905.zip](https://github.com/IDI-Systems/acre2/files/6050066/ts3dump_1614347856905.zip)

**Comment by jonpas** [comment]
I would fix this, but I still can't reproduce it at all. #956 is probably on a good track though.

**Comment by DeliciousJaffa** [comment]
The crashing appears to be prevented by #1110.
However I believe the reason it was crashing in the first place, that necessitated that check is still present. https://github.com/IDI-Systems/acre2/issues/855#issuecomment-629826381
Although, it's less of a concern now as it's just unexpected behaviour vs a crash.

**Comment by jonpas** [comment]
@BrettMayson Still happens with 2.9.1?

**Comment by BrettMayson** [comment]
Appears not

**Comment by DeliciousJaffa** [comment]
I've not had any more crashes, but the plugin still doesn't seem to be logically aware of multiple teamspeak servers properly (means I have to reload the plugin sometimes for it to work correctly)

**Comment by jonpas** [comment]
Good, thank you.

Correct, plugin is not and will not be aware of multiple servers, it will take the first one it sees.

**Comment by DeliciousJaffa** [comment]
> Correct, plugin is not and will not be aware of multiple servers, it will take the first one it sees.

That isn't quite an accurate description.
It uses whichever tab is active at the time for actions, rather than acting in the tab it was activated within, meaning it can break things if you go to a different TS tab to reply to a message etc.
[Example of this behaviour](https://github.com/IDI-Systems/acre2/blob/821bd25e7eb748e35aaf48b06002d564cc60a88d/extensions/src/ACRE2TS/TS3Client.cpp#L274).

I do think it should be bug fixed to operate as you described though, as performing the actions on any other connection than the one ACRE became connected to the game in, is clearly unintended/bugged behaviour.

**Comment by jonpas** [comment]
Yes, first one it sees = active one.

It's a bug, but not entirely unintended, it was never designed to support multiple servers. PRs welcome to improve this behaviour.
