### ISSUE TITLE
Radios Stop Working in large coops

### ISSUE THREAD

**Issue by SanchezMilsim** [IDI-Systems/acre2#875]
Mods: @ace;@ace_optionals;@acre2;@adv_aceCPR;@CBA_A3;@RHSAFRF;@RHSGREF;@RHSUSAF;@RHSUSAF_STKR_FIX;@Vcomai;
- Arma 3: Latest stable.
- CBA: 3.13.0
- ACRE2: v2.7.2
_Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!_ I cant do it because error only with more than 20 players and after hours of playing. Sorry. This mission is with previous acre version, yesterday we have same problem with latest version of acre. We dont have rpt of yesterday, i suppose error is the same. 

**Description:**
Radios stop working for all people, many times cant receive, cant emit making game unplayable. 

**Steps to reproduce:**
- Play mission, with 20-50 players more than 2 hours, with respawn and enjoy until radios stop working. 

**Expected behavior:**
Radios work all the game. 

**Where did the issue occur?**
- Dedicated

**Log Files:**
- RPT mission of ticket - https://mega.nz/#!DI4jyCSQ!zggIZW4H0flIEtNeSQs2E8WG8l5AinPvMH61naZ6unE
I cant use paste bin because is too long, and im not pro user.
-RPT other mission, with other mods, same problem. https://mega.nz/#!PUo1xCIC!WVdZJPkVSidB5G5gO1Xmp633z-JVLCltAmmLkAji-y8

**Additional context:**
No lag ingame, no desync. No fail in ace or other mods. 

DEDICATED SERVER SPECS
-Intel i7-6700K 4GHz
-64GB DDR4 2400MHz
-1x480GB   SSD
-Connection 250 Mbit/s Guaranteed (usually the double)

**Screenshots:**
-This is streaming of a friend, who record whats happening with radios (spanish) in mission of ticket. 
https://youtu.be/f0toL5wYbYM?t=14281
-Other streaming of different mission with same problem. https://youtu.be/yNwS9qYQ1to?t=10191

**Comment by sancron** [comment]
We also had the problem on a smaller scale. We only used the mods ACE, ACEX, ACRE2 and CBA. On one day we could play 8 hours until the problem occurred. But we had days when the problem appeared within the first hour.

We were able to detect the problem on both Linux and Windows servers. It didn't matter how many players were present or if more or less mods were loaded, or if there was a big co-op or a small internal skirmish.

**Description**
Radios stop working for all people.

**Steps to reproduce:**
- Start a Server with ACE, ACEX, ACRE2 and CBA
- Play Several hours and times using KP Liberation (Not modified)
- Play until randomly ACRE2 Radios stops working

**Expected behavior:**
Radios work all the game.

**Where did the issue occur?**
- Dedicated Server (Ubuntu 18.04.3)

**Logfiles**
- Client: https://pastebin.com/7Uu8BdbE
... more will follow try to collect from several People

**Comment by AndreasBrostrom** [comment]
My community also experiencing this this issue as well.
It stops working and may return.
Usaly drops 10-20min in to the mission

**Comment by Freddo3000** [comment]
Had the issue occur when mission was left idle for 5 hours (with headless clients) and then slotted and played. Radios randomly cease working for some people, but not others and may begin working again later. Respawning seems to accelerate the rate of issues appearing.

Restarting the mission resolves the issue, though that isn't really a good solution.

**Comment by Quailsnap** [comment]
Had this issue in a 90-man op over the weekend that went on for ~8.5 hours. People stopped being able to hear each other or be heard at seemingly random. Re-initializing with in-game script commands nor reloading the TS3 plugin fixed anything.

Interestingly enough, if I dropped my radio and picked it back up, one single transmission would go through just fine -- then nothing.

I was running -nologs so unfortunately I do not have an .RPT, but I will be asking around ...

**Comment by Ivorystate** [comment]
Having similar issues, but local will stop working as well for some people 
server RPT(2 parts):https://pastebin.com/WE4NWzia https://pastebin.com/weUUgjK6
client RPT(though it was my rpt and I didn't really have the issue as far as I remember): https://pastebin.com/Qk5iGnAr
I had a similar issue for a while where radios would just randomly stop working, but was fixed for a time by setting terrain loss to zero. Now we have a new issue even with those settings that worked before where after respawning, players will stop being able to talk in local or on the radio, until rejoining. Sometimes simply restarting teamspeak will fix it, sometimes not, seems a bit random. Pretty frustrating, if I can't find a fix I guess I'll just have to find an alternative to ACRE, but I really would rather fix it or at least mitigate it, as rejoining the game is quite disruptive to play. Any suggestions would be welcome. Maybe it has something to do with client fps because we were playing on rhspkl and some people had very low fps. We had about 5 or 6 people on at the time, and we had a similar issue a week back in vindicta but not as bad(only really happened for one guy and it may have been unrelated).

**Comment by nk3nny** [comment]
We have had the described issue with sessions  The following issue is relevant: https://github.com/IDI-Systems/acre2/issues/626

Our suspicion is that the error is related to cleaning and reassigning of radio IDs. Most commonly when players respawn.  It has tended to happen when airframes are in play-- especially when these move a long distance from the _center mass_ of ground assets/platoon. 

We have confirmed that our server FPS remains stable, as do our TS connections.  Gear scripts assign new 'blank' radios to reinforcing players-- i.e., no preassigned IDs are reused. 

Our main gripe is that the error is so difficult to debug. Restarting teamspeak only fixes the problem infrequently.  We would also appreciate if it was possible to do some sort of _nuclear solution_, a full reset of all radio IDs to see if these regenerate in some useful manner.

**Comment by Soldia1138** [comment]
This is maybe related to #876 | I suppose all of you have the Multipath Signal Calculation activated (default)?
We are going to have an internal testing on a possible fix this week on this matter.

**Comment by nk3nny** [comment]
@Soldia1138 
Recently changed from Multipath to single.  We've only really done one larger helicopter mission in which we faced no issues.  I intend to report back once we have developed more data.

**Comment by nk3nny** [comment]
After changing from multipath signal calculation to single _and_ removing all terrain coefficients we have experienced no radio breakdowns in the last 22 days.  This includes some rather extensive air ops with multiple airframes and ground-to-air callsigns. 

-k

**Comment by WolfSkin0** [comment]
> 
> 
> After changing from multipath signal calculation to single _and_ removing all terrain coefficients we have experienced no radio breakdowns in the last 22 days. This includes some rather extensive air ops with multiple airframes and ground-to-air callsigns.
> 
> -k

The unit I'm doing admin for is experiencing the same issue as mentioned by OP at the start. We'll try implementing this fix and report back if this fixes it for us too, just to confirm whether this is a complete fix for the issue

**Comment by jonpas** [comment]
Please do, but mind it is not a complete fix for the issue, only a workaround until LOS Multi-Path is fixed.

**Comment by jonpas** [comment]
> and removing all terrain coefficients

@nk3nny What happened when you only switched to LOS Simple, without removing all terrain coefficients?

**Comment by WolfSkin0** [comment]
> Please do, but mind it is not a complete fix for the issue, only a workaround until LOS Multi-Path is fixed.

Yh, that was clear. I can confirm it works for us too as a temp fix, so I can finally have the group's leadership stop breathing down my neck about it.

**Comment by nk3nny** [comment]
@jonpas I forgot to mention. We have reset terrain coef to 1 and will continue testing. First air op. of any scale is on Tuesday. 

I will report back as we develop more data.

**Comment by Quailsnap** [comment]
Is Longley-Rice working fine?

**Comment by tbeswick96** [comment]
I've been using Longley-Rice mostly with no problems. We lost comms when just above water in aircraft (3 birds within 200m of each other, ~50ft altitude, zero comms)
It has mostly been fine over LOS Multi-Path

**Comment by jonpas** [comment]
Linking issue with #820 as it seems to have the same root but different result.

**Comment by jonpas** [comment]
Should be fixed by #925 (LOS Multipath fix). Please reopen if you still experience this in upcoming 2.7.3 release.
